<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>        
    </head>
    <body>
        <header class="site-header">
            <div class="container">
                
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="/">My Play List</a>
                    </div>
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="/">Home</a></li>
                      <li class=""><a href="/topten"> Top 10 </a></li>
                	  <li class=""><a href="/addvideos"> Add Video </a></li>   
                      <li class=""><a href="/logout">Logout</a></li> 
                    </ul>
                  </div>
                </nav>
            </div>
        </header> <!-- .site-header -->
        <main class="main-content">
            <div class="fullwidth-block inner-content">
                <div class="container">
                    <div class="container">
                        <h4>Add videos</h4>
						<form method="post" action="addvideos" class="col-md-8" >
							<div style="margin-bottom: 20px;">							
								<div class="col-md-12  form-group">
									<?php if(isset($addvideo)) echo $addvideo; ?>										
								</div>							
							</div>
							<div style="margin-bottom: 20px;">							
								<div class="col-md-12  form-group">
									<input class="form-control" type="text" placeholder="Title video .." name="txttitle">
								</div>							
							</div>
							<div style="margin-bottom: 20px;">
								<div class="col-md-12  form-group">
									<input class="form-control" type="text" placeholder="link video .." name="txtlink">
								</div>	
							</div>
							<div style="margin-bottom: 20px;">
								<div class="col-md-12  form-group">
								<input class="btn btn-info" type="submit" value="Add Video" name="addvideo">
							</div>
							</div>
						</form>
                    </div>
                </div>
            </div>

                        
        </main> 
    </body>
</html>
