<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>        
    </head>
    <body>
        <header class="site-header">
            <div class="container">
                
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="/">My Play List</a>
                    </div>
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="/">Home</a></li>
                      <li class=""><a href="/topten"> Top 10 </a></li>
                      <li class=""><a href="/login">Login</a></li>     
                     
                    </ul>
                  </div>
                </nav>
            </div>
        </header> <!-- .site-header -->
			
		<main class="main-content">
			<div class="fullwidth-block inner-content">
				<div class="container">
					<h2 class="page-title" style="text-align: center;">Login To MyPlayList </h2>
					<div class="row">
						<div class="col-md-offset-3 col-md-6">
						
							<?php
							    if($messager!="")
							    {
							         echo $messager;
							    }
							?>
							<form method="post" action="login" >
								<div style="margin-bottom: 20px;">
									<input class="form-control" type="text" placeholder="User Name .." name="username">
								</div>
								<div style="margin-bottom: 20px;">
									<input class="form-control" type="Password" placeholder="Password..." name="password">
								</div>
								<div style="margin-bottom: 20px;">
									<input class="btn btn-info" type="submit" value="Login" name="login">
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

						
		</main> <!-- .main-content -->

		<footer class="site-footer">
			<div class="container">
				
			</div>
		</footer> <!-- .site-footer -->

	</div> <!-- #site-content -->
</body>

</html>