<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Login</title>        
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <!-- <script src="js/jquery-1.11.1.min.js"></script>
        <script src="js/bootstrap.min.js"></script>  -->   
        <script src="js/angular.js"></script>    
    </head>
    <body>
        <header class="site-header">
            <div class="container">
                
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
					<a class="navbar-brand" href="/">My YOUTUBE Playlist</a>
                    </div>
                    <ul class="nav navbar-nav">
                      <li class=""><a href="/">Home</a></li>
                      <li class=""><a href="/topten"> Top 10 </a></li>
                      <li class=""><a href="/search-video"> Search Video </a></li>
                      <li class="active"><a href="/login">Login</a></li>     
                      <li class=""><a href="/register">Register</a></li>  
                    </ul>
                  </div>
                </nav>
            </div>
        </header> <!-- .site-header -->
			
		<main class="main-content">
			<div class="fullwidth-block inner-content">
				<div class="container">
				<h2 class="page-title" style="text-align: center;">Login To My YOUTUBE Playlist </h2>
					<div class="row">
						<div class="col-md-offset-3 col-md-6">
							<div ng-app="myApp" ng-controller="formCtrl">
								<form novalidate>
									<div style="color: red; margin-bottom: 20px;">
										<p>{{Messager}}</p>
									</div>
									<div style="margin-bottom: 20px;">
										<input class="form-control" type="text" placeholder="User Name .." name="username" ng-model="user.userName" >
									</div>
									<div style="margin-bottom: 20px;">
										<input class="form-control" type="Password" placeholder="Password..." name="password"  ng-model="user.passWord">
									</div>									
								    <div style="margin-bottom: 20px;">
										<button class="btn btn-info" ng-click="login()">Login</button> 
									</div>
								  </form>							  	
							</div>
						</div>
					</div>
				</div>
			</div>

						
		</main> <!-- .main-content -->

		<footer class="site-footer">
			<div class="container">
				
			</div>
		</footer> <!-- .site-footer -->

	</div> <!-- #site-content -->
	<script>
	var app = angular.module('myApp', []);
	app.controller('formCtrl', function($scope, $http, $window ) {
	    $scope.login = function() {
	    	$scope.Messager = "";
	    	if($scope.user.userName.trim() == "")
	    	{
				$scope.Messager = "Please input username!";
	    		return;	 
	    	}
	    	if($scope.user.passWord.trim() == "")
	    	{
	    		$scope.Messager = "Please input password!";
	    		return;	    	
	    	}

	    	$http({
		        method : "POST",
		        url : "/login",    
				headers : {'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},
				data: { 'username': $scope.user.userName, 'password': $scope.user.passWord }
		    }).then(function mySuccess(response) {		    	
		    	$scope.Messager = response.data.messager;	
		    	if(response.data.url!="")
		    		$window.location.href = "/";	    	
		    }, function myError(response) {
		        $scope.Messager = response.statusText;
		    });	    	
	    }   
	     
	    $scope.Messager = "";
	    $scope.user = {userName:"", passWord:""};
	});
	</script>
</body>

</html>