<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title> Register </title>        
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script> -->
        <script src="js/angular.js"></script>
        <!-- <script src="js/bootstrap.min.js"></script>         -->
    </head>
    <body>
        <header class="site-header">
            <div class="container">
                
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="/">My Play List</a>
                    </div>
                    <ul class="nav navbar-nav">
                      <li class=""><a href="/">Home</a></li>
                      <li class=""><a href="/topten"> Top 10 </a></li>
                      <li class=""><a href="/search-video"> Search Video </a></li>
                      <li class=""><a href="/login">Login</a></li>     
                      <li class="active"><a href="/register">Register</a></li> 
                    </ul>
                  </div>
                </nav>
            </div>
        </header> <!-- .site-header -->
			
		<main class="main-content">
			<div class="fullwidth-block inner-content">
				<div class="container">
					<h2 class="page-title" style="text-align: center;">Register</h2>
					<div class="row">
						<div class="col-md-offset-3 col-md-6">
							<div ng-app="myApp" ng-controller="formCtrl">
								<form novalidate>
									<div style="margin-bottom: 20px;">
										<p>{{Messager}}</p>
									</div>
									<div style="margin-bottom: 20px;">
										<input class="form-control" type="text" placeholder="User Name .." name="username" ng-model="user.userName" >
									</div>
									<div style="margin-bottom: 20px;">
										<input class="form-control" type="Password" placeholder="Password..." name="password"  ng-model="user.passWord" ng-blur="checkRePassWord()">
									</div>
									<div style="margin-bottom: 20px;">
										<input class="form-control" type="Password" placeholder="Re-type Password..." name="repassword"  ng-model="user.rePassWord" ng-blur="checkRePassWord()">
										 <p>{{messagerRePass}}</p>
									</div>
								    <div style="margin-bottom: 20px;">
										<button class="btn btn-info" ng-click="register()">Register</button> 
										<button  class="btn btn-defaul" ng-click="reset()">RESET</button>
									</div>
								  </form>							  	
							</div>
						</div>
					</div>
				</div>
			</div>

						
		</main> <!-- .main-content -->

		<footer class="site-footer">
			<div class="container">
				
			</div>
		</footer> <!-- .site-footer -->

	</div> <!-- #site-content -->
	<script>
	var app = angular.module('myApp', []);
	app.controller('formCtrl', function($scope, $http) {
	    $scope.master = {userName:"", passWord:"", rePassWord: ""};
	    $scope.checkExists = false;
	    $scope.messagerRePass = "";
	    $scope.reset = function() {
	        $scope.user = angular.copy($scope.master);
	        $scope.messagerRePass = "";
	        $scope.Messager = "";	
	    };
	    $scope.register = function() {
	    	if($scope.user.passWord.trim() == "")
	    		return;	 
	    	if($scope.messagerRePass != "")
	    		return;	    	
	    	$http({
		        method : "POST",
		        url : "/checkUserExists",    
				headers : {'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},
				data: { 'username': $scope.user.userName, 'password': $scope.user.passWord }
		    }).then(function mySuccess(response) {		    	
		    	$scope.checkExists = response.data.checkExists;	
		    	console.log($scope.checkExists);    	
		    	if($scope.checkExists)
		        	$scope.Messager = "user is exists";			       
	        	else
	        	{
		        	$scope.Messager = "";	
	        		$http({
			        method : "POST",
				        url : "/register",
				        headers : {'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},
						data: { 'username': $scope.user.userName, 'password': $scope.user.passWord }
				    }).then(function mySuccess(response) {		    	
				    	$scope.Messager = response.data.messager;
				    }, function myError(response) {
				        $scope.Messager = response.statusText;
				    });		       
	        	}
		    }, function myError(response) {
		        $scope.Messager = response.statusText;
		    });	    	
	    }
	    $scope.checkRePassWord = function() {
	    	if($scope.user.passWord !=  $scope.user.rePassWord)
	    		$scope.messagerRePass = "password incorrect";
	    	else
	    		$scope.messagerRePass = "";
	    }	    
	    $scope.reset();
	});
	</script>

</body>

</html>