<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title> Register </title>        
		<link rel="stylesheet" href="css/bootstrap.min.css">
        <base href="/app/myplaylist/src/">
    </head>
    <body>
        <header class="site-header">
            <div class="container">
                
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="/">My YOUTUBE Playlist</a>
                    </div>
                    <ul class="nav navbar-nav">
                      <li class=""><a href="/">Home</a></li>
                      <li class=""><a href="/topten"> Top 10 </a></li>
                      <li class=""><a href="/search-video"> Search Video </a></li>
                      <li class=""><a href="/login">Login</a></li>     
                      <li class="active"><a href="/register">Register</a></li> 
                    </ul>
                  </div>
                </nav>
            </div>
        </header> <!-- .site-header -->
			
		<main class="main-content">
			<div class="fullwidth-block inner-content">
                <app-root></app-root>
			</div>

						
		</main> <!-- .main-content -->

		<footer class="site-footer">
			<div class="container">
				
			</div>
		</footer> <!-- .site-footer -->

	</div> <!-- #site-content -->
	<script type="text/javascript" src="/app/myplaylist/dist/inline.bundle.js"></script>
    <script type="text/javascript" src="/app/myplaylist/dist/polyfills.bundle.js"></script>
    <script type="text/javascript" src="/app/myplaylist/dist/styles.bundle.js"></script>
    <script type="text/javascript" src="/app/myplaylist/dist/vendor.bundle.js"></script>
    <script type="text/javascript" src="/app/myplaylist/dist/main.bundle.js"></script>
</body>

</html>