<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Home</title>
        <link rel="stylesheet" href="/css/bootstrap.min.css">
        <script src="/js/jquery-1.11.1.min.js"></script>
        <script src="/js/bootstrap.min.js"></script>  
        <link rel="stylesheet" href="/css/style.css">  
    </head>
    <body>
        <header class="site-header">
            <div class="container">
                
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="/">My YOUTUBE Playlist</a>
                    </div>
                    <ul class="nav navbar-nav">
                      <li class="active"><a href="/">Home</a></li>
                      <li class=""><a href="/topten"> Top 10 </a></li>
                      <li class=""><a href="/search-video"> Search Video </a></li>
                     <?php  if( isset($_SESSION['username']) ): ?>
                            
                            <li class=""><a href="/addvideos"> Add Video </a></li>   
                            <li class=""><a href="/logout">Logout</a></li>           
                      <?php else:  ?>                         
                        <li class=""><a href="/login">Login</a></li>
                        <li class=""><a href="/register">Register</a></li>     
                      <?php endif; ?>
                    </ul>
                  </div>
                </nav>
            </div>
        </header> <!-- .site-header -->
        <main class="main-content">
            <div class="fullwidth-block inner-content">
                <div class="container">                    
                    <div class="container">
                        <?php
                        if(count($videos) > 0):   
                            $videoplay = $videos[0];
                            if(isset($play)) {
                                if(count($play) > 0)
                                    $videoplay = $play[0];
                            }
                        ?>
                       <div style="padding: 10px; margin-bottom: 20px;">
                            <div class="row">
                                <h4><?php echo $videoplay["title"] ?></h4>
                            </div>
                            <div class="row">
                            <iframe width="560" height="315" src="<?php echo "https://www.youtube.com/embed/". $videoplay["link"] ?>" frameborder="0" allowfullscreen></iframe>
                            <div>
                            <div class="row">
                            <?php  if( isset($_SESSION['username']) ): ?>
                                <a style="margin-left: 20px;" href="/votes/<?php echo $videoplay["id"]; ?>" class="btn btn-info" <?php if(isset($disableBtnLike)) echo $disableBtnLike;?> > Like </a> 
                            <?php endif; ?>  
                                &nbsp;&nbsp;&nbsp; Number like: <?php echo $videoplay["votes"]; ?>
                            </div>
                        </div>  
                         <div style="padding: 10px; margin-bottom: 20px;">
                        <?php
                             if(isset($topten)):
                                ?>

                                <div class="row">
                                    <h4> Top 10 voted videos</h4>
                                </div>
                                <?php 
                                endif;
                            $i = 1;
                            foreach($videos as $video): 
                               
                                echo "<div class='row'><h4> ".$i." - (".$video["votes"].") votes - <a href='/play/".$video["id"]."'>".$video["title"]."</a></h4></div>";
                                ?>
                                
                                              

                        <?php 
                            $i++;
                            endforeach; ?>
                        </div>         
                        <?php else: ?>
                        <p>No current tickets</p>
                        <?php endif; ?>
                        
                    </div>
                </div>
            </div>

                        
        </main> 
    </body>
</html>
